name: GitHub Actions
run-name: Running GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment with Poetry
        run: poetry install

      - name: Run tests
        run: poetry run pytest
